/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "table.h"
#include "value.h"
#include "object.h"
#include "vm.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TableInit(void);
extern void test_TableSetBool(void);
extern void test_TableSetNumber(void);
extern void test_TableSetNil(void);
extern void test_TableSetSameKey();
extern void test_TableGrowthRate();


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/testTable.c");
  run_test(test_TableInit, "test_TableInit", 17);
  run_test(test_TableSetBool, "test_TableSetBool", 24);
  run_test(test_TableSetNumber, "test_TableSetNumber", 34);
  run_test(test_TableSetNil, "test_TableSetNil", 45);
  run_test(test_TableSetSameKey, "test_TableSetSameKey", 55);
  run_test(test_TableGrowthRate, "test_TableGrowthRate", 70);

  return UnityEnd();
}
